name: action-setup-tools
description:
  GitHub Action that installs and provisions supported tools for workflow steps
  in self-hosted runners. This relies on the agent having supported tooling
  installed.
outputs:
  go:
    description:
      The version of golang that has been installed and is ready for use.
  node:
    description:
      The verison of Node.js that has been installed and is ready for use.
  java:
    description:
      The version of Java that has been installed and is ready for use.
  python:
    description:
      The version of Python that has been installed and is ready for use.
  terraform:
    description:
      The version of Terraform that has been installed and is ready for use.
runs:
  using: "node20"
  main: "dist/main/index.js"
