name: action-setup-tools
description: Intialize self-hosted tool versions
inputs:
  go:
    description: The desired version of golang to install.
    required: false
  node:
    description: The desired version of Node.js to install.
    required: false
  java:
    description: The desired version of Java to install.
    required: false
  kotlin:
    description: The desired version of Kotlin to install.
    required: false
  python:
    description: The desired version of Python to install.
    required: false
  terraform:
    description: The desired version of Terraform to install.
    required: false
outputs:
  go:
    description:
      The version of golang that has been installed and is ready for use.
  node:
    description:
      The version of Node.js that has been installed and is ready for use.
  java:
    description:
      The version of Java that has been installed and is ready for use.
  kotlin:
    description:
      The version of Kotlin that has been installed and is ready for use.
  python:
    description:
      The version of Python that has been installed and is ready for use.
  terraform:
    description:
      The version of Terraform that has been installed and is ready for use.
runs:
  using: "node16"
  main: "../dist/main/index.js"
