name: Action Test
description: Tests the action directly
inputs:
  use-versions:
    description: "Use versions"
    default: "true"
    required: true
runs:
  using: composite
  steps:
    - name: Install and build package
      shell: bash
      run: npm ci
    - name: Run action using inputs
      if: inputs.use-versions == 'true'
      uses: ./versions
      with:
        go: 1.17.6
        java: 17.0.2-tem
        node: 16.13.2
        python: 3.10.2
        terraform: 1.1.5
    - name: Create version files
      shell: bash
      if: inputs.use-versions != 'true'
      run: |
        # Write version files
        echo "java=17.0.2-tem" > .sdkmanrc
        echo "16.13.2" > .node-version
        echo "3.10.2" > .python-version
        echo "1.17.6" > .go-version
        echo "1.1.5" > .terraform-version
    - name: Run action using version files
      if: inputs.use-versions != 'true'
      uses: ./
    - shell: bash
      run: |
        # Check versions
        go version | grep "1.17.6"
        java -version 2>&1 | grep "17.0.2"
        node --version | grep "16.13.2"
        python --version || grep "3.10.2"
        terraform --version | grep "1.1.5"
