# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other
# source files.  We need to make sure the checked-in `index.js` actually matches
# what we expect it to be.
name: Check

on:
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build is up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dist check
        uses: open-turo/actions-gha/node-check-dist@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
