name: "CI"
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/lint@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # Runs unit tests
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-tools
      - uses: open-turo/actions-gha/test@v1
        with:
          checkout-repo: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # Build and run the action from this repo to test full functionality
  action:
    name: Test action with inputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-test
        with:
          use-versions: false

  # Build and run the action from this repo to test full functionality
  action-versions:
    name: Test action with version files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-test
        with:
          use-versions: true
