name: "CI"
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/lint@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 20

  fast:
    name: Test / Fast
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/test@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          TEST_FAST: "1"
          NO_TEST_JAVA: "1"

  # Runs unit tests
  test:
    name: Test
    needs: [lint, fast]
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/test@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NO_TEST_JAVA: "1"

  action-test-inputs:
    name: Test / Action with Inputs
    needs: [lint, fast]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/action-test
        with:
          use-versions: false

  action-test-versions:
    name: Test / Action with Version Files
    needs: [lint, fast]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/action-test
        with:
          use-versions: true

  action-test-input-overrides-file:
    name: Test / Input Overrides Version File
    needs: [lint, fast]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create conflicting version files
        run: |
          echo "1.17.3" > .go-version
          echo "20.12.3" > .nvmrc
          echo "3.12.3" > .python-version
          echo "1.0.3" > .terraform-version
          echo "java=17.0.3-librca" > .sdkmanrc

      - name: Run action with input versions
        uses: ./.github/actions/action-test
        with:
          use-versions: true

      - name:
          Verify versions should match the values in
          ./.github/actions/action-test
        shell: bash
        run: |
          # Check versions
          go version | grep "1.17.1"
          java -version 2>&1 | grep "17.0.1"
          node --version | grep "20.12.1"
          python3 --version | grep "3.12.1"
          terraform --version | grep "1.1.1"

  action-test-double-run:
    name: Test / Run Setup Twice
    needs: [lint, fast]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: First setup
        uses: ./.github/actions/action-test
        with:
          use-versions: true

      - name: Overwrite previous setup setup
        uses: ./
        with:
          go: 1.17.2
          java: 17.0.2-tem
          node: 20.12.2
          python: 3.12.2
          terraform: 1.1.2

      - name: Verify overwritten versions should match the previous step
        run: |
          go version | grep "1.17.2"
          java -version 2>&1 | grep "17.0.2"
          node --version | grep "20.12.2"
          python3 --version 2>&1 | grep "3.12.2"
          terraform --version | grep "1.1.2"
