name: Release

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/lint@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  fast:
    name: Test / Fast
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/test@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          TEST_FAST: "1"

  # Runs unit tests
  test:
    name: Test
    needs: [lint, fast]
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/test@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # Build and run the action from this repo to test full functionality
  action:
    name: Test / Inputs
    needs: [lint, fast]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/action-test
        with:
          use-versions: false
        env:
          IGNORE_INSTALLED: "true"

  release:
    needs:
      - lint
      - fast
      - test
      - action
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: open-turo/actions-gha/release@v1
