name: Release

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/lint@v1

  #  test:
  #    name: Test
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: open-turo/actions-gha/test@v1

  release:
    needs:
      - lint
    #      - test
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: open-turo/actions-gha/release@v1
